- hosts: coordinator
  tasks:
    - name: Add labs to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].wireguard_ip }} {{ item }}"
        state: present
      loop: "{{ groups['labs'] }}"
      become: yes

    - name: Create .ssh directory
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: "0700"

    - name: Add .ssh/config
      blockinfile:
        path: /home/{{ ansible_user }}/.ssh/config
        block: |
          Host {{ item }}
            HostName {{ hostvars[item].wireguard_ip }}
            User {{ hostvars[item].ansible_user }}
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
        create: true
      loop: "{{ groups['labs'] }}"

- hosts: labs
  tasks:
    - name: Add public SSH key of coordinator
      authorized_key:
        user: "{{ ansible_user }}"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP0ZVlD9TmfAXL53Vq7V9WKE3KPomOa1jINyflrPWAlJ"

    - name: Install required packages
      apt:
        name:
          - pipx
          - microcom
          - ser2net
          - socat
          - iptables
          - iptables-persistent
        state: present
        update_cache: yes
      become: yes

    - name: Install labgrid packages
      community.general.pipx:
        name: labgrid
        state: present
      notify:
        - Restart labgrid-exporter
        - Restart labgrid-coordinator

    - name: Create labgrid folder
      file:
        path: /etc/labgrid
        state: directory
      become: yes

    - name: Create tftp folder with 777
      file:
        path: /srv/tftp/
        state: directory
        mode: "0777"
      become: yes

    - name: Copy exporter configuration
      template:
        src: files/exporter/{{ ansible_host }}.yaml
        dest: /etc/labgrid/exporter.yaml
      become: yes
      notify:
        - Restart labgrid-exporter

    - name: Install dnsmasq
      apt:
        name:
          - dnsmasq
        state: present
        update_cache: yes
      become: yes
      notify:
        - Restart dnsmasq

    - name: Configure dnsmasq
      template:
        src: files/exporter/dnsmasq.conf
        dest: /etc/dnsmasq.conf
      become: yes
      notify:
        - Restart dnsmasq

    - name: Start and enable dnsmasq
      service:
        name: dnsmasq
        state: started
        enabled: yes
      become: yes

    - name: Copy labgrid-coordinator.service
      template:
        src: files/coordinator/labgrid-coordinator.service
        dest: /etc/systemd/system/labgrid-coordinator.service
      become: yes
      notify:
        - Restart labgrid-coordinator

    - name: Create coordinator directory
      file:
        path: /home/{{ ansible_user }}/labgrid-coordinator
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      become: yes

    - name: Start and enable labgrid-coordinator
      service:
        name: labgrid-coordinator
        state: started
        enabled: yes
      become: yes

    - name: Copy labgrid-exporter.service
      template:
        src: files/exporter/labgrid-exporter.service
        dest: /etc/systemd/system/labgrid-exporter.service
      become: yes
      notify:
        - Restart labgrid-exporter

    - name: Start and enable labgrid-exporter
      service:
        name: labgrid-exporter
        state: started
        enabled: yes
      become: yes

    - name: Add developers group to sudoers for labgrid-bound-connect
      lineinfile:
        path: /etc/sudoers
        line: "%ALL ALL = NOPASSWD: /usr/local/sbin/labgrid-bound-connect"
        validate: "visudo -cf %s"
      become: yes

    - name: Install labgrid-bound-connect
      copy:
        src: files/labgrid-bound-connect
        dest: /usr/local/sbin/labgrid-bound-connect
        mode: "0755"
      become: yes

    - name: Create /var/cache/labgrid
      file:
        path: /var/cache/labgrid
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      become: yes

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: yes
        reload: yes
      become: yes

    - name: Make IP forwarding persistent
      copy:
        content: "net.ipv4.ip_forward = 1"
        dest: /etc/sysctl.d/99-ip-forward.conf
        mode: "0644"
      become: yes

  handlers:
    - name: Restart labgrid-exporter
      systemd:
        daemon_reload: yes
        name: labgrid-exporter
        state: restarted
      become: yes

    - name: Restart labgrid-coordinator
      systemd:
        daemon_reload: yes
        name: labgrid-coordinator
        state: restarted
      become: yes

    - name: Restart dnsmasq
      systemd:
        daemon_reload: yes
        name: dnsmasq
        state: restarted
      become: yes
